### ISSUE TITLE
Quick feedback

### ISSUE THREAD

**Issue by robmadole** [gtri/lowendinsight#2]
Hey @kitplummer 

Didn't have a lot of time to pass through but here are some surface thoughts:

1. You have a Mix task but [it's not prefixed](https://github.com/gtri/lowendinsight/blob/develop/lib/mix/tasks/lei.ex#L5). If you rename it to `Mix.Tasks.Lei.Analyze` similar to how say [Phoenix does](https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phx.server.ex#L1) you'll get a nice namespaces task
1. The main return value for the meat `analyze/2` function returns a big ole Map. It might be good to think about [a struct](https://elixir-lang.org/getting-started/structs.html).
1. Would atoms be better for some of [these return values](https://github.com/gtri/lowendinsight/blob/develop/lib/risk_logic.ex#L17) (like `{:ok, :low}`)
1. I noticed your docs have a lot of spec-styles stuff (x returns y kinda thing) Have you seen [Typespecs](https://hexdocs.pm/elixir/typespecs.html)?
1. The pattern in methods [like this](https://github.com/gtri/lowendinsight/blob/develop/lib/git_module.ex#L164) can lead to `MatchError` if the thing doesn't return `{:ok, _}`. You might look at using [with](https://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html#with) 
1. [This is just itching](https://github.com/gtri/lowendinsight/blob/develop/lib/project_ident.ex#L90) for some [Meta Programming](https://pragprog.com/book/cmelixir/metaprogramming-elixir) (I highly recommend that book, taught me a ton)

Pretty cool library! I'll have to run it on some of our stuff and see what the numbers look like 😎

**Comment by kitplummer** [comment]
Thanks man!  Super appreciated, and all good things.  I'm definitely just getting intro'd to Elixir, and maybe a public library is the way to force myself to address the idioms head on.  :D 

I'll probably pick some of these things out, and put into their own issue for easy tracking and stuff I can delegate.  You've also nailed some of the things that are in my must-learn queue.  I despise the amount of code I've to process the project type stuff.  Thanks for the pointer for that book for sure, a new one to me.

**Comment by kitplummer** [comment]
Moved the tasks here to new issues.  Thanks again @robmadole for the input.  Have some new functionality, like being able to scan a local project the LEI has been added as a dependency to.  LEI adds a `mix lei.scan` task to that enviro, and will run the scan against your dependencies in the mix.
