### ISSUE TITLE
Parser for Python Projects

### ISSUE THREAD

**Issue by haldihri3** [gtri/lowendinsight#84]
- create a parser for `*requirements*.txt`to
   -- ignore comment lines and line-end comments
   -- account for line continuations
   -- account for repo links in the file
   -- extract dependency and version

Note: There are other format options for `requirements.txt` that we should explore
- retrieve the repo links for Python packages
   -- PyPi JSON API?: `https://pypi.org/pypi/<package_name>/json`
        --- source code can be found under ["info"]["project_urls"]["Source Code"] or ["info"]["download_url"]
- create a test file

**Comment by kitplummer** [comment]
There are a couple different "central" repo options within the Python landscape: PyPi, and Conda.  We'll need to think about how to manage that.  Worth investigating the impact of that on LEI things.
