### ISSUE TITLE
Git log throws :enoent

### ISSUE THREAD

**Issue by jronmi** [gtri/lowendinsight#94]
** (stop) :enoent
    :erlang.open_port({:spawn_executable, '/opt/apps/Module/git/2.15.1/bin/git'}, [{:cd$
    (elixir 1.10.2) lib/system.ex:802: System.cmd/3
    lib/git.ex:105: Git.execute_command/4
    lib/git.ex:83: Git.log!/2
    lib/git_module.ex:327: GitModule.git_log_split/2
    lib/git_module.ex:132: GitModule.get_last_n_commits/2
    lib/git_module.ex:183: GitModule.get_last_2_delta/1
    lib/git_module.ex:167: GitModule.get_recent_changes/1
Function: &AnalyzerModule.analyze/3
    Args: ["https://github.com/aliyun/alibabacloud-sdk", "mix task", %{counter: #PID<0.$

13:54:11.288 [error] Task #PID<0.92.0> started from #PID<0.1078.0> terminating
** (stop) :enoent
    :erlang.open_port({:spawn_executable, '/opt/apps/Module/git/2.15.1/bin/git'}, [{:cd$
    (elixir 1.10.2) lib/system.ex:802: System.cmd/3
    lib/git.ex:105: Git.execute_command/4
    lib/git.ex:83: Git.log!/2
    lib/git_module.ex:327: GitModule.git_log_split/2
    lib/git_module.ex:132: GitModule.get_last_n_commits/2
    lib/git_module.ex:183: GitModule.get_last_2_delta/1
    lib/git_module.ex:167: GitModule.get_recent_changes/1
Function: &AnalyzerModule.analyze/3
    Args: ["https://github.com/aliyun/alibabacloud-sdk", "mix task", %{counter: #PID<0.$
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (ErlangError) Erlang error: :enoent
        :erlang.open_port({:spawn_executable, '/opt/apps/Module/git/2.15.1/bin/git'}, [$
        (elixir 1.10.2) lib/system.ex:802: System.cmd/3
        lib/git.ex:105: Git.execute_command/4
        lib/git.ex:83: Git.log!/2
        lib/git_module.ex:327: GitModule.git_log_split/2
        lib/git_module.ex:132: GitModule.get_last_n_commits/2
        lib/git_module.ex:183: GitModule.get_last_2_delta/1
        lib/git_module.ex:167: GitModule.get_recent_changes/1

**Comment by kitplummer** [comment]
This appears to be a local problem.  I was able to scan that particular repo no problems on my machine.  Going to check on ICEHAMMER cluster now.

**Comment by kitplummer** [comment]
Yeah, this appears to work.  The issue must be related to the local clone, or the ability to do something on the local FS.  There were no other errors besides this?

**Comment by jronmi** [comment]
The iss
